#!/bin/bash

APACHE2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installeerimine")

if [ $APACHE2 -eq 0 ]
then
	echo "Apache2 paigaldus hakkab"
	pause
	apt install apache2 -y
elif [ $APACHE2 -eq 1 ]
then
	echo "Apache2 on paigaldus lõpetatud"
	pause
	systemctl status apache2
fi
