#!/bin/bash

mysql=$(dpkg-query -W -f='${Status}' mysql 2>/dev/null | grep -c "ok installeeritud")
if [ $mysql -eq 0 ]
then
	echo "mysql paigaldus hakkab"
	pause
	apt install mysql-client mysql-server -y #mysql serveri ja kliendi install

elif [ $mysql -eq 1 ]
then
	echo "mysql on paigaldatud"
	pause
	systemctl status mysql
fi
